# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'StrongVPN' do
  # Comment the next line if you don't want to use dynamic frameworks

# add the Firebase pod for Google Analytics
#pod 'Firebase/Core'
#pod 'Firebase/Firestore'
#pod 'Firebase/Auth'

# witwork app
pod 'PureLayout'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SwiftDate'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
pod 'lottie-ios'
pod 'SwiftyStoreKit'
pod "Macaw", "0.9.7"
pod 'Google-Mobile-Ads-SDK'
pod 'SVProgressHUD'

# rxswift
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxRelay'
pod 'RxAppState'
pod 'RxReachability'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  end
 end
end
